import argparse
import os
import uuid
from datetime import datetime
import logging
from logging.handlers import RotatingFileHandler
import extract_predict
import cluster
import plot
import discriminate

def setup_logging(log_file):
    """
    Configure and return a logger that writes to both console and file.
    Implements rotating file handler and timestamped log file names.
    """
    logger = logging.getLogger("pockethunter")
    logger.setLevel(logging.DEBUG)

    # Configure file handler with rotating capabilities
    file_handler = RotatingFileHandler(
        log_file,
        maxBytes=10*1024*1024,  # 10MB
        backupCount=5,
        encoding="utf-8"
    )
    file_handler.setLevel(logging.DEBUG)

    # Configure console handler
    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.INFO)

    # Format handlers
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S"
    )
    file_handler.setFormatter(formatter)
    console_handler.setFormatter(formatter)

    # Add handlers to logger
    logger.addHandler(file_handler)
    logger.addHandler(console_handler)

    return logger

def get_config(output_dir, overwrite):
    """Generate configuration based on the specified output directory."""

    os.makedirs(output_dir, exist_ok=overwrite)

    # Timestamp for job ID
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S") 
    job_id = f"{timestamp}_{str(uuid.uuid4())[:4]}"

    logger = setup_logging(os.path.join(output_dir,f"log_{job_id}.log"))
    
    config = {'logger': logger}

    return config

def full_pipeline(args, config):
    try:

        """Run the full pipeline."""
        logger = config['logger']
        logger.info("Starting the full pocket detection pipeline.")
        outfolder = args.outfolder
        
        # Modify args.outfolder temporarily to enable extract_to_pdb to write to a subfolder inside main outfolder here.
        args.outfolder = os.path.join(outfolder,'pdbs')

        # Extract frames from XTC to PDB files
        extract_to_pdb(args, config)

        # Add args.infolder needed by detect_pockets.
        args.infolder = args.outfolder

        # Modify args.outfolder temporarily again for detect_pockets to write a subfolder.
        args.outfolder = os.path.join(outfolder,'pockets')

        # Detect pockets on PDB files
        detect_pockets(args, config)

        # Modify args.infolder for cluster_pockets again.
        args.infolder = args.outfolder

        # Set args.infile to the pockets.csv file generated by detect_pockets
        args.infile = os.path.join(args.infolder, "pockets.csv")

        # Modify args.outfolder again
        args.outfolder = os.path.join(outfolder,'pocket_clusters')

        # Perform clustering, identify representatives.
        cluster_pockets(args, config)

        logger.info("Full pocket detection pipeline completed successfully.")

    except Exception as e:
        logger.error(f"Error in pocket detection process: {str(e)}")
        raise

def extract_to_pdb(args, config):
    """Extract frames from XTC to PDB files."""
    xtc_file = args.xtc
    topology_file = args.topology
    stride = args.stride
    outfolder = args.outfolder
    overwrite = args.overwrite
    logger = config['logger']
    logger.info(f"Extracting frames from XTC file: {xtc_file}")

    # Convert XTC to PDB
    pdb_files = extract_predict.xtc_to_pdb(xtc_file, topology_file,
        stride, outfolder, overwrite, config)

    # Write PDB list to a file
    logger.info("Writing PDB list file")
    pdb_list_file = os.path.join(outfolder, 'pdb_list.ds')
    extract_predict.write_pdb_list(outfolder, pdb_list_file, config)

def detect_pockets(args, config):
    """Detect pockets on PDB files in input folder using p2rank."""
    infolder = os.path.abspath(args.infolder)
    outfolder = args.outfolder
    numthreads = args.numthreads
    logger = config['logger']
    pdb_list_file = os.path.join(infolder,'pdb_list.ds')
    novis = args.novis
    compress = args.novis
    overwrite = args.overwrite

    # Run P2Rank on the PDB list
    extract_predict.run_p2rank(pdb_list_file, outfolder, numthreads, novis, compress, overwrite, config)

def cluster_pockets(args, config):
    """Identifies representative pockets via clustering."""
    infile = os.path.abspath(args.infile)
    outfolder = args.outfolder
    method = args.method
    depth = args.depth
    min_prob = args.min_prob

    cluster.cluster_pockets(
        infile=args.infile,
        outfolder=args.outfolder,
        method=args.method,
        depth=args.depth,
        min_prob=args.min_prob,
        config=config,
        hierarchical=args.hierarchical
    )

def plot_clustermap(args):
    """Generate cluster map visualization from clustering results."""
    infolder = os.path.abspath(args.infolder)

    plot.plot_clustermap(
        infolder=infolder
    )

def discriminate_conformations(args, config):
    """Rank cluster representatives by active/decoy discrimination."""
    logger = config['logger']
    logger.info("Starting discrimination analysis.")
    df = discriminate.run_discrimination(
        cluster_dir=os.path.abspath(args.cluster_dir),
        actives_sdf=os.path.abspath(args.actives),
        decoys_sdf=os.path.abspath(args.decoys),
        outfolder=os.path.abspath(args.outfolder),
        pdb_dir=os.path.abspath(args.pdb_dir) if args.pdb_dir else None,
        alpha=args.alpha,
        width=args.width,
    )
    logger.info("Discrimination complete. Results saved to %s", args.outfolder)
    logger.info("\n%s", df[['cluster_id', 'frame', 'roc_auc', 'ef1', 'ef5']].to_string(index=False))

def main():
    # Initialize argument parser
    parser = argparse.ArgumentParser(
        description="CLI tool to identify representative small-molecular binding pockets "
         " in protein molecular simulation trajectories using p2rank and via a simple clustering analysis"
    )
    parser.add_argument('--output', type=str, default='.', help='Base output directory (default: current directory)')
    
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # Full pipeline
    parser_full = subparsers.add_parser("full_pipeline", help="Full pipeline for pocket prediction.")
    parser_full.add_argument("--xtc", required=True, help="Input XTC trajectory file.")
    parser_full.add_argument("--topology", required=True, help="Topology PDB/GRO file.")
    parser_full.add_argument("--depth", type=int, default=4, help="Clustering depth.")
    parser_full.add_argument("--method", type=str,  default="dbscan", choices=["hierarchical","dbscan"], 
                                help='Clustering method. Choose between hierarchical and dbscan.')
    parser_full.add_argument("--min_prob",type=float, default=0.5, help="Minimum ligand-binding probability for clustering (default: 0.5).")
    parser_full.add_argument('--novis', action='store_true', help='Do not keep visualizations generated by p2rank.')
    parser_full.add_argument('--compress', action='store_true', help='Compress p2rank output directory.')
    parser_full.add_argument("--numthreads", type=int, default=4, help="Number of parallel threads (default: 4)."),
    parser_full.add_argument("--stride", type=int, default=1, help="Stride applied for frame extraction."),
    parser_full.add_argument("--overwrite", action='store_true', help="Overwrite existing output directory.")
    parser_full.add_argument('--outfolder', type=str, default='.', help='Output folder.')
    parser_full.add_argument('--hierarchical', action='store_true', help='Perform hierarchical clustering within DBSCAN clusters.')


    # Extract frames from XTC
    parser_convert = subparsers.add_parser("extract_to_pdb", help="Extract frames from XTC to PDB files.")
    parser_convert.add_argument("--xtc", required=True, help="Input XTC trajectory file.")
    parser_convert.add_argument("--topology", required=True, help="Topology PDB/GRO file.")
    parser_convert.add_argument("--stride", type=int, default=1, help="Stride applied for frame extraction.")
    parser_convert.add_argument('--outfolder', type=str, help='Output folder.')
    parser_convert.add_argument('--overwrite', action='store_true', help='Overwrite existing output directory.')

    # Predict pockets
    parser_detect = subparsers.add_parser("detect_pockets", help="Detect pockets on PDB files in input folder using p2rank.")
    parser_detect.add_argument("--numthreads", type=int, default=4, help="Number of parallel threads (default: 4).")
    parser_detect.add_argument('--infolder', type=str, help='Input folder containing PDB files (should be generated by extract_to_pdb).')
    parser_detect.add_argument('--outfolder', type=str, help='Output folder.')
    parser_detect.add_argument('--novis', action='store_true', help='Do not keep visualizations generated by p2rank.')
    parser_detect.add_argument('--compress', action='store_true', help='Compress p2rank output directory.')
    parser_detect.add_argument('--overwrite', action='store_true', help='Overwrite existing output directory.')

    # Cluster pockets
    parser_cluster = subparsers.add_parser("cluster_pockets",help="Clusters identified pockets based on binary feature vectors "
                                           "denoting residue presence in the pocket.")
    parser_cluster.add_argument("--infile", type=str, help='Input CSV file produced by predict_pockets (pockets.csv).')
    parser_cluster.add_argument("--outfolder", type=str, help='Output folder.')
    parser_cluster.add_argument("--method", type=str, default="dbscan", choices=["hierarchical","dbscan"], 
                                help='Clustering method. Choose between hierarchical and dbscan.')
    parser_cluster.add_argument("--depth", type=int, default=4, 
                                help='Clustering depth parameter for identification of representatives pockets from '
                                'hierarchical clustering.')
    parser_cluster.add_argument("--min_prob",type=float, default=0.5, help="Minimum ligand-binding probability for clustering (default: 0.5).")
    parser_cluster.add_argument('--hierarchical', action='store_true', help='Perform hierarchical clustering within DBSCAN clusters.')
    parser_cluster.add_argument('--overwrite', action='store_true', help='Overwrite existing output directory.')

    # Plot cluster map
    parser_plot = subparsers.add_parser("plot_clustermap", help="Generate cluster map visualization from clustering results.")
    parser_plot.add_argument("--infolder", type=str, help='Input folder containing clustering results (output from cluster_pockets).')

    # Discrimination analysis
    parser_disc = subparsers.add_parser(
        "discriminate",
        help="Rank cluster representatives by active/decoy pharmacophore discrimination."
    )
    parser_disc.add_argument(
        "--cluster_dir", required=True,
        help="Path to pocket_clusters output directory (contains cluster_representatives.csv)."
    )
    parser_disc.add_argument(
        "--actives", required=True,
        help="Path to actives SDF file (max 200 molecules)."
    )
    parser_disc.add_argument(
        "--decoys", required=True,
        help="Path to decoys SDF file (max 2000 molecules)."
    )
    parser_disc.add_argument(
        "--outfolder", required=True,
        help="Output folder for discrimination results."
    )
    parser_disc.add_argument(
        "--pdb_dir", type=str, default=None,
        help="Directory containing representative PDB files (required when residue IDs "
             "use CHAIN_RESNUM format, e.g. from p2rank). Typically the 'pdbs/' folder "
             "from the extract step."
    )
    parser_disc.add_argument(
        "--alpha", type=float, default=0.9,
        help="Weight of 1D cosine score in combined scoring (0-1). "
             "Default 0.9."
    )
    parser_disc.add_argument(
        "--width", type=float, default=2.5,
        help="Gaussian kernel width in Å for 3D feature overlap. Default 2.5."
    )
    parser_disc.add_argument(
        "--overwrite", action='store_true',
        help="Overwrite existing output directory."
    )

    args = parser.parse_args()

    if args.command is None:
        parser.print_help()
        return  # Exit without running anything
    
    # Load configuration with user-specified output directory
    if not args.command == "plot_clustermap":
        config = get_config(args.outfolder, args.overwrite)

    # Execute commands
    if args.command == "full_pipeline":
        full_pipeline(args, config)
    elif args.command == "extract_to_pdb":
        extract_to_pdb(args, config)
    elif args.command == "detect_pockets":
        detect_pockets(args, config)
    elif args.command == "cluster_pockets":
        cluster_pockets(args, config)
    elif args.command == "plot_clustermap":
        plot_clustermap(args)
    elif args.command == "discriminate":
        discriminate_conformations(args, config)
    else:
        parser.print_help()

if __name__ == "__main__":
    main()